/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One card game entry in Naibi. Every field is written from scratch in the project's own words; no text is copied or closely paraphrased from any source.
 */
export interface CardGame {
  /**
   * Slug identifying the game. Must match the filename (games/<id>.json).
   */
  id: string;
  /**
   * Display name of the game.
   */
  name: string;
  /**
   * Other names the game is commonly known by. May be empty.
   */
  aliases: string[];
  /**
   * Primary family the game belongs to, chosen by its core mechanic.
   */
  category: "trick-taking" | "shedding" | "rummy-type" | "solitaire" | "casino" | "matching-collecting" | "bluffing";
  players: {
    min: number;
    max: number;
    /**
     * Single best player count. Ranges belong in the prose, not here.
     */
    ideal: number;
  };
  /**
   * What you need to deal, in plain English, e.g. "1 standard deck (52 cards)" or "2 standard decks plus 4 jokers (108 cards)". Written for a person to read; the machine-readable version is in "equipment".
   */
  decks: string;
  /**
   * The same requirement as "decks", but as data, so an app can answer "what can I play with what I own?" without parsing prose.
   */
  equipment: {
    /**
     * How many ordinary 52-card decks you must OWN to play at the minimum player count. Games needing a stripped deck still count the packs they are built from: Euchre is 1, Pinochle is 2. Use 0 for a game that needs a purpose-built pack you cannot make from ordinary cards, such as hanafuda, and name it in special_deck.
     */
    standard_decks: number;
    /**
     * How many jokers the game requires. 0 when jokers are unused or optional.
     */
    jokers: number;
    /**
     * Set when play uses a stripped or purpose-built pack rather than a full one, e.g. "24-card euchre deck". Null for ordinary play.
     */
    special_deck: string | null;
    /**
     * How many decks are needed from a given player count upward, e.g. {"6": 2} for a game that wants a second pack from six players. Read as: the value for the largest key at or below the table size, falling back to standard_decks. Omit when the requirement never changes. Use it for per-player games too -- Nertz needs one deck each, so every count gets an entry.
     */
    decks_by_players?: {
      [k: string]: number;
    };
    /**
     * Anything needed beyond cards, e.g. a cribbage board. Usually empty.
     *
     * @maxItems 4
     */
    other: string[];
  };
  /**
   * How the table starts: deal, layout, dealer selection, anything built before the first turn.
   */
  setup: string;
  /**
   * The starting table as data, so a setup diagram can be drawn rather than illustrated by hand. Optional: include it where the arrangement is worth seeing, omit it where 'everyone holds cards' says everything (most pure trick-taking games). Rows are drawn top to bottom and each row is centred, which is what makes a pyramid a pyramid and a cross a cross.
   */
  layout?: {
    /**
     * One line under the diagram, for anything the shapes cannot say.
     */
    caption?: string;
    /**
     * How many rows from the top are drawn overlapping one another, for layouts where a card is physically covered by the cards below it — a pyramid, or TriPeaks. Leave unset (0) and every row is drawn clear of its neighbours, which is right for a grid or a clock face. Set it where the covering IS the rule, because a diagram that draws those cards apart contradicts the rule it is illustrating.
     */
    overlapping_rows?: number;
    /**
     * @minItems 1
     * @maxItems 8
     */
    rows: [
      [
        {
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        },
        ...{
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        }[]
      ],
      ...[
        {
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        },
        ...{
          /**
           * What the pile is for. Drives how it is drawn. "gap" is an empty spacer used to position the others.
           */
          kind:
            | "tableau"
            | "foundation"
            | "stock"
            | "waste"
            | "reserve"
            | "free-cell"
            | "hand"
            | "discard"
            | "meld"
            | "trick"
            | "gap";
          /**
           * Caption under the pile, e.g. "Foundations". Omit on gaps.
           */
          label?: string;
          /**
           * How many identical piles sit side by side. Defaults to 1.
           */
          repeat?: number;
          /**
           * Cards dealt to each pile at the start. One number for all of them, or one per pile when they differ (Klondike's tableau is [1,2,3,4,5,6,7]). Omit when the count varies with the player count or is not fixed.
           */
          cards?: number | [number, ...number[]];
          /**
           * How the cards sit. "last-up" is the Klondike case: face down with the final card turned up. Defaults to "up".
           */
          face?: "up" | "down" | "last-up";
          /**
           * Whether the pile is spread so every card shows, rather than squared into a stack. Defaults to true for a tableau and false for everything else, which is usually right — set it explicitly where it is not, such as a discard pile you are allowed to take from part-way down.
           */
          fan?: boolean;
        }[]
      ][]
    ];
  };
  /**
   * How a turn works and how the hand proceeds: turn order, legal moves, restrictions, how the hand ends. The ceiling is a guard against sprawl rather than a target — the median entry is around 3,000 characters. Contract Bridge sits near the top and has earned it; if a simpler game is pressing the limit, the entry probably needs editing rather than more room.
   */
  play: string;
  /**
   * Captioned rows of named cards, for the things prose explains badly: what order cards rank in, and what a valid combination actually looks like. Optional, and worth including only where the answer is not obvious -- a ranking strip for a game that ranks ace high teaches nothing.
   *
   * @minItems 1
   * @maxItems 4
   */
  figures?: [
    {
      /**
       * "ranking" for cards in order of power, "meld" for a valid (or invalid) combination.
       */
      kind: "ranking" | "meld";
      /**
       * What the figure shows, e.g. "Trump ranking when diamonds are trump".
       */
      caption: string;
      /**
       * @minItems 1
       * @maxItems 4
       */
      rows: [
        {
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        },
        ...{
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        }[]
      ];
    },
    ...{
      /**
       * "ranking" for cards in order of power, "meld" for a valid (or invalid) combination.
       */
      kind: "ranking" | "meld";
      /**
       * What the figure shows, e.g. "Trump ranking when diamonds are trump".
       */
      caption: string;
      /**
       * @minItems 1
       * @maxItems 4
       */
      rows: [
        {
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        },
        ...{
          /**
           * Caption to the left of the row, e.g. "Valid run".
           */
          label?: string;
          /**
           * Set false to mark a row as a counter-example, drawn struck through. Useful for the mistakes people actually make, like running king-ace-two.
           */
          valid?: boolean;
          /**
           * @minItems 1
           * @maxItems 14
           */
          cards: [
            {
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            },
            ...{
              /**
               * The card as a player would say it: "A♠", "10♦", "J♥". Use the suit symbols. "?" for any card, "Jkr" for a joker.
               */
              face: string;
              /**
               * Small caption under this one card, e.g. "Right bower".
               */
              note?: string;
            }[]
          ];
        }[]
      ];
    }[]
  ];
  /**
   * Ids of shared figures from shared/figures.json to show on this game, appended after any inline `figures`. Use this where a figure is genuinely identical across several games — the poker hand rankings are the same in every poker variant — so an error gets corrected once rather than in every entry that repeats it. Readers still see the figure on every page; only the source is shared.
   *
   * @minItems 1
   * @maxItems 6
   */
  figure_refs?: [string, ...string[]];
  /**
   * What winning looks like and how points (if any) are counted.
   */
  goal_and_scoring: string;
  /**
   * Where the game comes from and anything else worth knowing that is not a rule: origin, age, how the name is used elsewhere, why it looks the way it does. Optional, and rendered AFTER the rules and the variants -- a reader with a deck in hand wants the deal, not the eighteenth century. Keep material that changes what someone does at the table in `setup` instead: that a game needs a pack you cannot substitute, or that one player is playing against the other two, is orientation rather than background.
   */
  background?: string;
  /**
   * Hand size by player count, and anything taken out of the deck to make it come out even. Include it where this actually varies -- Hearts strips cards at 3, 5 and 6 players -- and omit it where one number covers every case, since "thirteen each" needs no table.
   *
   * @minItems 1
   * @maxItems 10
   */
  deal?: [
    {
      /**
       * The player count this row applies to.
       */
      players: number;
      /**
       * Cards dealt to each player. Use 0 where the whole deck is shared out and the count follows from the deck size.
       */
      hand: number;
      /**
       * Cards taken out of the deck at this player count, e.g. "2♦". Omit when none are.
       */
      removed?: string;
      /**
       * Anything else specific to this count.
       */
      note?: string;
    },
    ...{
      /**
       * The player count this row applies to.
       */
      players: number;
      /**
       * Cards dealt to each player. Use 0 where the whole deck is shared out and the count follows from the deck size.
       */
      hand: number;
      /**
       * Cards taken out of the deck at this player count, e.g. "2♦". Omit when none are.
       */
      removed?: string;
      /**
       * Anything else specific to this count.
       */
      note?: string;
    }[]
  ];
  /**
   * Point values as a lookup, for games where scoring is something you consult mid-hand rather than remember: Cribbage's combinations, Canasta's card values, Pinochle's melds. The prose in goal_and_scoring still explains how scoring works; this is only the numbers.
   *
   * @minItems 2
   * @maxItems 24
   */
  scoring_table?: [
    {
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    },
    {
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    },
    ...{
      /**
       * What scores, e.g. "Fifteen" or "Each ace".
       */
      item: string;
      /**
       * What it is worth, as text so ranges and conditions fit: "2", "-10", "20 each".
       */
      value: string;
      /**
       * A short qualifier, e.g. "only if it takes a trick".
       */
      note?: string;
    }[]
  ];
  /**
   * A few well-known variations. Not intended to be exhaustive.
   *
   * @minItems 2
   * @maxItems 8
   */
  variants: [
    {
      name: string;
      description: string;
      /**
       * The player range this variant serves, when it differs from the game's own. Omit unless the variant's prose states a count plainly -- an absent range costs a missed recommendation, a wrong one costs a reader a game that does not work at their table.
       */
      players?: {
        min: number;
        max: number;
      };
    },
    {
      name: string;
      description: string;
      /**
       * The player range this variant serves, when it differs from the game's own. Omit unless the variant's prose states a count plainly -- an absent range costs a missed recommendation, a wrong one costs a reader a game that does not work at their table.
       */
      players?: {
        min: number;
        max: number;
      };
    },
    ...{
      name: string;
      description: string;
      /**
       * The player range this variant serves, when it differs from the game's own. Omit unless the variant's prose states a count plainly -- an absent range costs a missed recommendation, a wrong one costs a reader a game that does not work at their table.
       */
      players?: {
        min: number;
        max: number;
      };
    }[]
  ];
  /**
   * How much there is to learn before a first game, not how hard it is to play well.
   */
  difficulty: "simple" | "easy" | "medium" | "complex";
  /**
   * Rough playing time as a range, e.g. "15-30", or an open-ended floor, e.g. "60+".
   */
  duration_minutes: string;
  /**
   * Facets for filtering. Drawn from a controlled vocabulary so search stays consistent across the collection.
   *
   * @minItems 1
   * @maxItems 10
   */
  tags: [
    (
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    ),
    ...(
      | "family-friendly"
      | "kids"
      | "party"
      | "partnership"
      | "solo"
      | "two-player"
      | "large-group"
      | "quick"
      | "long-game"
      | "bluffing"
      | "memory"
      | "strategy"
      | "luck"
      | "speed"
      | "reflex"
      | "counting"
      | "betting"
      | "beginner-friendly"
      | "classic"
      | "travel"
      | "no-table-needed"
    )[]
  ];
  /**
   * Names of sources checked while verifying the rules. Attribution as good practice; the write-up itself is original.
   *
   * @minItems 1
   * @maxItems 12
   */
  sources_consulted: [string, ...string[]];
  /**
   * When this entry's prose was last read against its sources, and a fingerprint of the prose as it stood at that moment. The fingerprint is what makes the record mean anything: edit any of the prose fields afterwards and the validator reports the entry as changed since it was checked, rather than letting a date sit there implying a check that no longer covers the text. Absent means never checked, which is not the same as checked and clean.
   */
  checked?: {
    /**
     * ISO date the check was made, e.g. "2026-08-01".
     */
    date: string;
    /**
     * Fingerprint of the entry's prose at check time. Which fields that covers is PROSE_FIELDS in the naibi package; naming them here instead is how this description came to claim three of them for a day after a fourth joined.
     */
    prose: string;
    /**
     * Which of `sources_consulted` this entry was actually read against at check time, by name. `sources_consulted` is attribution and lists everything looked at; several entries name sources that were never pulled, so it cannot answer how many sources a check really had. This can. Two is the floor because one source cannot corroborate itself. Absent means the check predates this record and how many sources it had is not known, which is not the same as one.
     *
     * @minItems 2
     * @maxItems 12
     */
    sources?: [string, string, ...string[]];
    /**
     * A later, wording-only rewrite of the prose: `date` is when it was changed and `prose` is the fingerprint as it now stands, while `checked.prose` above keeps naming the text that was read against the sources on `checked.date`. Present means the entry's wording has moved since its check and its facts have not — which is what removing a verbatim run does, and the reason restamping with the rewrite's date would be a lie: nobody re-read the sources that day. Absent means the prose is still the prose that was checked. See docs/decisions/0025-a-wording-fix-amends-the-check.md.
     */
    reworded?: {
      /**
       * ISO date the wording was rewritten, e.g. "2026-08-15". Never earlier than `checked.date`.
       */
      date: string;
      /**
       * Fingerprint of the entry's prose as it now stands. Differs from `checked.prose` by construction: equal fingerprints would record a rewrite that did not happen.
       */
      prose: string;
    };
    /**
     * When the prose that hangs off this entry's structured data — variant names and descriptions, the layout caption, figure captions, row labels and card notes, scoring-table items and notes — was last read against its sources, and a fingerprint of it as it stood then. `checked.prose` above covers `PROSE_FIELDS` and nothing else, so without this the 31% of the corpus's prose that lives out here is covered by no stamp at all: copied wording passes, and an edit after a check goes unnoticed. Both were demonstrated rather than inferred. It carries its own date because the two advance at different rates, which is the real situation. Absent means this prose has never been compared, which is not the same as compared and clean. See docs/decisions/0026-a-second-fingerprint-for-the-nested-prose.md.
     */
    nested?: {
      /**
       * ISO date the nested prose was read against its sources, e.g. "2026-08-15".
       */
      date: string;
      /**
       * Fingerprint of the nested prose at check time. Which fields that covers is `nestedProse` in the naibi package; enumerating them here instead is how the sibling description above came to claim three fields for a day after a fourth joined.
       */
      prose: string;
      /**
       * Which of `sources_consulted` the nested prose was actually compared against, by name. Same rule and same floor as the sibling above: two, because one source cannot corroborate itself.
       *
       * @minItems 2
       * @maxItems 12
       */
      sources?: [string, string, ...string[]];
      /**
       * A later, wording-only rewrite of the nested prose. Same meaning as the sibling above and for the same reason: removing a verbatim run from a variant description raises exactly the question removing one from `play` raises, and one answer for both is better than two.
       */
      reworded?: {
        /**
         * ISO date the wording was rewritten, e.g. "2026-08-15". Never earlier than `checked.date`.
         */
        date: string;
        /**
         * Fingerprint of the entry's prose as it now stands. Differs from `checked.prose` by construction: equal fingerprints would record a rewrite that did not happen.
         */
        prose: string;
      };
    };
  };
}
